### PR TITLE
libretro: fix video pitch

### PR DESCRIPTION
**Pull request by trioan**

### CODE REVIEW

**Comment by negativeExponent** [comment]
when MEDNAFEN_CORE_GEOMETRY_MAX_W was changed, FB_WIDTH should have been changed as well. this would avoid the necessity of this PR

**Comment by trioan** [comment]
The internal renderer engine has a 1365 hard scanline limit I believe. So increasing FB_WIDTH I think would screw the dot timing. But I have to recheck this .. can't rely on memory.

**Comment by negativeExponent** [comment]
how can FB_WIDTH screw dot clocks? when this is just use to create the maximum buffer size that can be used. if increasing that causes problems (which i cant replicate on my android even with 1024 width games), then something else is wrong somewhere else.

**Comment by tooncoon** [comment]
Android Shields have this alignment problem in many cores.
https://github.com/libretro/beetle-pce-libretro/issues/3

Stella had this same problem also.
https://github.com/stella-emu/stella/issues/504
https://github.com/stella-emu/stella/commit/daf4c0e71511c38008ddd38222dca0507744064d#diff-d9c454db439aaa82b1aeb2dacd371051
https://github.com/stella-emu/stella/commit/4d75dcb462084416beb13c167a5c8df658160444

**Comment by trioan** [comment]
I will let someone who has an OpenGLES device create patch and deal with these cores. I'd rather not help then.

**Pull request closed without merging**
