### PR TITLE
[Do not merge] Update libchdr to latest upstream

### PR DESCRIPTION
**Pull request by negativeExponent**
Fix: https://github.com/libretro/beetle-pce-libretro/issues/75

### CODE REVIEW

**Comment by LibretroAdmin** [comment]
If it can be changed to a git subtree I can merge it

**Comment by sonninnos** [comment]
What is the holdup? The deps are currently already there as is, like with many other cores.

**Comment by LibretroAdmin** [comment]
Alright let's try it I guess

**Comment by negativeExponent** [comment]
It appears that this was reverted. Can we just provide pce cores with a system-based libchdr instead for platforms that works with it? The initial zstd was supported years ago and the request for it is well overdue...

**Comment by negativeExponent** [comment]
pcsx-reamed has dont the same and updated libchdr without revert. can we use that libchdr deps instead for all pce cores?

@LibretroAdmin

**Comment by hizzlekizzle** [comment]
I'm afraid I don't know enough about the libchdr situation to comment, but I'll ask around.

**Comment by negativeExponent** [comment]
ditto: 2 similar PR's and PR not addressed since last posting

**Pull request merged**
